# Generated by Django 3.1.5 on 2021-01-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='body',
            field=models.CharField(max_length=80),
        ),
    ]
