# Generated by Django 3.1.5 on 2021-01-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210116_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='response',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
