# Generated by Django 3.1.5 on 2021-01-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_userquery_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='accuracy',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
